# Generated by Django 3.0.8 on 2021-01-30 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Symptom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Disease')),
                ('characteristic', models.CharField(blank='True', max_length=200, null='True', verbose_name='Characteristic')),
            ],
        ),
        migrations.CreateModel(
            name='Disease',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Disease')),
                ('symptoms', models.ManyToManyField(blank='True', to='core.Symptom')),
            ],
        ),
    ]
