# Generated by Django 3.0.8 on 2021-01-30 06:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20210130_0749'),
    ]

    operations = [
        migrations.AddField(
            model_name='symptom',
            name='category',
            field=models.ForeignKey(blank='True', null='True', on_delete=django.db.models.deletion.CASCADE, to='core.Category'),
            preserve_default='True',
        ),
    ]
