# Generated by Django 3.0.8 on 2021-01-30 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_symptom_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['pk']},
        ),
        migrations.AddField(
            model_name='disease',
            name='description',
            field=models.TextField(blank='True', null='True', verbose_name='description'),
            preserve_default='True',
        ),
    ]
