# Generated by Django 3.0.8 on 2021-02-15 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_survey'),
    ]

    operations = [
        migrations.AddField(
            model_name='survey',
            name='symptoms',
            field=models.ManyToManyField(blank='True', null='True', to='core.Symptom'),
            preserve_default='True',
        ),
    ]
